"""Pydantic schemas for the API.

Organized to mirror the three Postgres schemas defined in setup.sql:

* `common` — building blocks shared by every model (pagination, problem
  details, timestamps).
* `core`   — domains, studies, outcomes/anchors, messages, sources, the
  knowledgebase, and avatars.
* `runs`   — study runs, their approval gates, live progress, and results.
* `platform` — async jobs, LLM providers/keys, credits/usage, and users.

Import from this package directly, e.g. `from app.schemas import Study`.
"""

from app.schemas.common import (
    APIModel,
    Page,
    PageMeta,
    Priority,
    Problem,
    Timestamps,
)
from app.schemas.core import (
    Anchor,
    AnchorSet,
    AnchorSetUpdate,
    Avatar,
    AvatarCreate,
    AvatarDraft,
    AvatarList,
    AvatarScope,
    AvatarSource,
    AvatarUpdate,
    Chunk,
    ChunkList,
    Domain,
    DomainCreate,
    DomainList,
    DomainType,
    DomainUpdate,
    IngestStatus,
    Intent,
    Knowledgebase,
    KnowledgebaseSearchRequest,
    KnowledgebaseSearchResult,
    Message,
    MessageCreate,
    MessageList,
    MessageUpdate,
    Outcome,
    OutcomeUpdate,
    Panel,
    PanelMember,
    PanelUpdate,
    Scale,
    Source,
    SourceAnalysis,
    SourceList,
    SourceUpdate,
    Study,
    StudyCreate,
    StudyList,
    StudyStatus,
    StudyUpdate,
    Sufficiency,
)
from app.schemas.platform import (
    AnchorAssistRequest,
    CreditBalance,
    Job,
    JobKind,
    JobStatus,
    LedgerEntry,
    LedgerList,
    MessageAssistRequest,
    Model,
    ModelType,
    PersonaAssistRequest,
    Provider,
    ProviderKey,
    ProviderKeyCreate,
    Role,
    StudyNameAssistRequest,
    StudyNameSuggestion,
    Usage,
    User,
)
from app.schemas.runs import (
    AvatarReaction,
    ExportFormat,
    ExportRequest,
    MessageResult,
    ModelConfig,
    RankingEntry,
    RecommendationTier,
    Run,
    RunCreate,
    RunEstimate,
    RunEvent,
    RunEventType,
    RunList,
    RunResults,
    RunStatus,
    RunStatusView,
    ScoreDistribution,
)

__all__ = [  # noqa: RUF022 — grouped by schema, sorted within each group
    # common
    "APIModel",
    "Page",
    "PageMeta",
    "Priority",
    "Problem",
    "Timestamps",
    # core
    "Anchor",
    "AnchorSet",
    "AnchorSetUpdate",
    "Avatar",
    "AvatarCreate",
    "AvatarDraft",
    "AvatarList",
    "AvatarScope",
    "AvatarSource",
    "AvatarUpdate",
    "Chunk",
    "ChunkList",
    "Domain",
    "DomainCreate",
    "DomainList",
    "DomainType",
    "DomainUpdate",
    "IngestStatus",
    "Intent",
    "Knowledgebase",
    "KnowledgebaseSearchRequest",
    "KnowledgebaseSearchResult",
    "Message",
    "MessageCreate",
    "MessageList",
    "MessageUpdate",
    "Outcome",
    "OutcomeUpdate",
    "Panel",
    "PanelMember",
    "PanelUpdate",
    "Scale",
    "Source",
    "SourceAnalysis",
    "SourceList",
    "SourceUpdate",
    "Study",
    "StudyCreate",
    "StudyList",
    "StudyStatus",
    "StudyUpdate",
    "Sufficiency",
    # platform
    "AnchorAssistRequest",
    "CreditBalance",
    "Job",
    "JobKind",
    "JobStatus",
    "LedgerEntry",
    "LedgerList",
    "MessageAssistRequest",
    "Model",
    "ModelType",
    "PersonaAssistRequest",
    "Provider",
    "ProviderKey",
    "ProviderKeyCreate",
    "Role",
    "StudyNameAssistRequest",
    "StudyNameSuggestion",
    "Usage",
    "User",
    # runs
    "AvatarReaction",
    "ExportFormat",
    "ExportRequest",
    "MessageResult",
    "ModelConfig",
    "RankingEntry",
    "RecommendationTier",
    "Run",
    "RunCreate",
    "RunEstimate",
    "RunEvent",
    "RunEventType",
    "RunList",
    "RunResults",
    "RunStatus",
    "RunStatusView",
    "ScoreDistribution",
]
